package info.piepgras.cryptvault.ui

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.FilterChip
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import info.piepgras.cryptvault.CryptVaultApp
import info.piepgras.cryptvault.R
import info.piepgras.cryptvault.prefs.AppPrefs
import info.piepgras.cryptvault.security.sensitive
import info.piepgras.cryptvault.share.ContainerKind
import info.piepgras.cryptvault.share.SharePolicy
import info.piepgras.cryptvault.share.ShareService
import info.piepgras.cryptvault.unlock.PasswordPolicy

/**
 * "Share" of one or more items (BUILD_BRIEF.md §7.2): pick the container, get a generated
 * six-word passphrase (or type one that passes the policy), copy it for the separate channel,
 * see the size and the 15 MB warning, then hand the container to the share sheet — or share
 * the files as they are.
 */
@Composable
fun ShareContainerDialog(
    itemCount: Int,
    estimatedSize: Long,
    onShareEncrypted: (ContainerKind, CharArray) -> Unit,
    onSharePlain: () -> Unit,
    onDismiss: () -> Unit,
) {
    val context = LocalContext.current
    val container = CryptVaultApp.container(context)
    var kind by rememberSaveable { mutableStateOf(AppPrefs.containerKind(context)) }
    var generated by rememberSaveable { mutableStateOf(true) }
    var phrase by rememberSaveable { mutableStateOf(PasswordPolicy.suggest()) }
    var typed by rememberSaveable { mutableStateOf("") }
    var showNotice by rememberSaveable { mutableStateOf(!AppPrefs.deliverabilityNoticeShown(context)) }
    val current = if (generated) phrase else typed
    val score = remember(typed) { if (typed.isBlank()) 0 else PasswordPolicy.check(typed).score }
    val verdict = SharePolicy.check(kind, current, score)
    val tooBig = estimatedSize > SharePolicy.WARN_BYTES

    if (showNotice) {
        InfoDialog(
            title = stringResource(R.string.share_deliverability_title),
            text = stringResource(R.string.share_deliverability_body),
            onDismiss = { showNotice = false; AppPrefs.setDeliverabilityNoticeShown(context) },
        )
        return
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        properties = secureDialogProperties(),
        title = { Text(stringResource(R.string.share_dialog_title)) },
        text = {
            Column(Modifier.verticalScroll(rememberScrollState())) {
                Text(stringResource(R.string.share_dialog_help), style = MaterialTheme.typography.bodySmall)
                Spacer(Modifier.height(8.dp))
                Row {
                    for (k in ContainerKind.entries) {
                        FilterChip(selected = kind == k, onClick = { kind = k; AppPrefs.setContainerKind(context, k) }, label = { Text(stringResource(ShareService.kindName(k))) })
                        Spacer(Modifier.width(6.dp))
                    }
                }
                Text(stringResource(ShareService.openers(kind)), style = MaterialTheme.typography.bodySmall)
                Spacer(Modifier.height(12.dp))
                Row {
                    FilterChip(selected = generated, onClick = { generated = true }, label = { Text(stringResource(R.string.share_pass_generated)) })
                    Spacer(Modifier.width(6.dp))
                    FilterChip(selected = !generated, onClick = { generated = false }, label = { Text(stringResource(R.string.share_pass_typed)) })
                }
                if (generated) {
                    Text(phrase, style = MaterialTheme.typography.titleMedium, modifier = Modifier.sensitive())
                    Row {
                        TextButton(onClick = { phrase = PasswordPolicy.suggest() }) { Text(stringResource(R.string.share_pass_regenerate)) }
                        TextButton(onClick = { container.clipboard.copy(phrase) }) { Text(stringResource(R.string.action_copy)) }
                    }
                } else {
                    OutlinedTextField(
                        value = typed, onValueChange = { typed = it }, label = { Text(stringResource(R.string.share_pass_label)) }, singleLine = true,
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password, autoCorrectEnabled = false),
                        isError = typed.isNotEmpty() && verdict !is SharePolicy.Verdict.Ok,
                        supportingText = { if (typed.isNotEmpty() && verdict is SharePolicy.Verdict.TooWeak) Text(stringResource(R.string.share_pass_too_weak, (verdict as SharePolicy.Verdict.TooWeak).needScore)) },
                        modifier = Modifier.fillMaxWidth().sensitive(),
                    )
                }
                Spacer(Modifier.height(8.dp))
                Text(androidx.compose.ui.res.pluralStringResource(R.plurals.share_size_items, itemCount, itemCount, Format.size(estimatedSize)), style = MaterialTheme.typography.bodySmall)
                if (tooBig) Text(stringResource(R.string.share_size_warning), color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
                Spacer(Modifier.height(4.dp))
                Text(stringResource(R.string.share_pass_separately), style = MaterialTheme.typography.bodySmall)
            }
        },
        confirmButton = {
            TextButton(onClick = { onShareEncrypted(kind, current.toCharArray()) }, enabled = verdict is SharePolicy.Verdict.Ok) { Text(stringResource(R.string.share_encrypted)) }
        },
        dismissButton = {
            Row {
                TextButton(onClick = onDismiss) { Text(stringResource(R.string.action_cancel)) }
                TextButton(onClick = onSharePlain) { Text(stringResource(R.string.share_plain)) }
            }
        },
    )
}
